---

- name: Install httpd and php on centos
  dnf:
    name:
      - httpd
      - php
    state: present

- name: start and enable httpd
  service:
    name: httpd
    state: started
    enabled: yes

