---

- name: Add Repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    filename: grafana.list

- name: Install Package
  apt:
    name: grafana
    state: latest
    update_cache: yes
